# detection pipeline with full analysis
# runs all detectors and generates a report

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(__file__)), 'scripts'))

import time
import json
import joblib

from scripts.consumer import read_packets, window_packets, analyze_window
from scripts.attacks import (
    check_flood, check_port_scan, check_ssh_bruteforce,
    check_dns_amplification, check_c2_beaconing, check_dns_exfiltration,
    MITRE
)

MODEL_PATH = "models/isolation_forest.joblib"

def generate_report(all_alerts, total_packets, total_windows, source_file):
    """ writes a detailed findings report """
    report = []
    report.append("=" * 60)
    report.append("NetDetect - Traffic Analysis Report")
    report.append("=" * 60)
    report.append(f"\nSource: {source_file}")
    report.append(f"Packets analyzed: {total_packets}")
    report.append(f"Time windows: {total_windows}")
    report.append(f"Alerts triggered: {len(all_alerts)}")
    report.append(f"Time: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    report.append("\n" + "-" * 60)
    report.append("DETECTION SUMMARY")
    report.append("-" * 60)

    # group by type
    by_type = {}
    for a in all_alerts:
        t = a["type"]
        if t not in by_type:
            by_type[t] = []
        by_type[t].append(a)

    for attack_type, alerts in sorted(by_type.items()):
        mitre = alerts[0].get("mitre", "N/A")
        severities = [a["severity"] for a in alerts]
        max_sev = max(severities, key=lambda x: {"HIGH": 3, "MEDIUM": 2, "LOW": 1}.get(x, 0))
        avg_conf = sum(a["confidence"] for a in alerts) / len(alerts)

        report.append(f"\n[{attack_type}]")
        report.append(f"  MITRE: {mitre}")
        report.append(f"  Severity: {max_sev}")
        report.append(f"  Confidence: {avg_conf:.0f}%")
        report.append(f"  Occurrences: {len(alerts)}")
        report.append(f"  Sample: {alerts[0]['desc']}")

    report.append("\n" + "-" * 60)
    report.append("FULL ALERT LOG")
    report.append("-" * 60)

    for i, a in enumerate(all_alerts, 1):
        report.append(f"\n{i}. [{a['severity']}] {a['type']}")
        report.append(f"   {a['desc']}")
        report.append(f"   Confidence: {a['confidence']:.0f}%")

    report.append("\n" + "-" * 60)
    report.append("MITRE ATT&CK MAPPING")
    report.append("-" * 60)

    mapped = set()
    for a in all_alerts:
        if a["mitre"] not in mapped:
            report.append(f"\n  {a['mitre']}")
            mapped.add(a["mitre"])

    report.append("\n" + "=" * 60)
    report.append("Report generated by NetDetect")
    report.append("=" * 60)

    report_path = "data/analysis_report.txt"
    with open(report_path, 'w') as f:
        f.write('\n'.join(report))
    print(f"\nreport saved to {report_path}")
    return '\n'.join(report)

def main():
    print("=" * 50)
    print("NetDetect - Network Anomaly Detection")
    print("=" * 50)

    # figure out source file
    queue_file = "data/packet_queue.jsonl"

    if not os.path.exists(queue_file):
        print("no queue file found. run producer.py first")
        print("or: python scripts/generate_traffic.py")
        sys.exit(1)

    print("\nloading model...")
    model = None
    if os.path.exists(MODEL_PATH):
        model = joblib.load(MODEL_PATH)
        print(f"  loaded isolation forest from {MODEL_PATH}")
    else:
        print("  no ml model. running rule-based only")

    print("\nreading packets...")
    packets = read_packets()
    total_packets = len(packets)
    print(f"  {total_packets} packets loaded")

    windows = window_packets(packets)
    total_windows = len(windows)
    print(f"  grouped into {total_windows} windows (5s each)")

    all_alerts = []

    for i, w in enumerate(windows):
        stats = analyze_window(w)

        # run all detectors on this window
        alerts = []
        alerts.extend(check_flood(stats))
        alerts.extend(check_port_scan(stats))
        alerts.extend(check_ssh_bruteforce(w, windows))
        alerts.extend(check_dns_amplification(w))
        alerts.extend(check_c2_beaconing(w, windows, all_alerts))
        alerts.extend(check_dns_exfiltration(w))

        # ml detection if model loaded
        if model:
            features = np.array([
                stats["packet_count"],
                stats["byte_count"],
                stats["unique_dst_port_count"],
                stats["syn_count"],
                stats["tcp_count"],
                stats["udp_count"],
                stats["packets_per_sec"],
                stats["bytes_per_sec"],
            ]).reshape(1, -1)
            score = model.decision_function(features)[0]
            if score < -0.3:
                alerts.append({
                    "type": "ML_ANOMALY",
                    "severity": "MEDIUM",
                    "desc": f"isolation forest score={score:.3f}",
                    "mitre": MITRE["ML_ANOMALY"],
                    "confidence": min(abs(score) * 100, 95),
                })

        if alerts:
            sevs = [a["severity"] for a in alerts]
            high_count = sevs.count("HIGH")
            print(f"\n  window {i+1}: {stats['packet_count']} pkts - {len(alerts)} alerts ({high_count} high)")
            for a in alerts[:3]:
                icon = {"HIGH": "!!!", "MEDIUM": "!!", "LOW": "!"}.get(a["severity"], "?")
                print(f"    {icon} [{a['type']}] {a['desc']}")
            if len(alerts) > 3:
                print(f"    ... +{len(alerts)-3} more")
            all_alerts.extend(alerts)
        else:
            print(f"  window {i+1}: {stats['packet_count']} pkts - normal")

    print("\n" + "=" * 50)
    print(f"analysis complete: {total_packets} packets, {total_windows} windows")
    print(f"total alerts: {len(all_alerts)}")

    if all_alerts:
        report = generate_report(all_alerts, total_packets, total_windows, queue_file)
        print("\n" + report)

    # save alerts to json for dashboard
    with open("data/alerts.json", 'w') as f:
        json.dump(all_alerts, f, indent=2)
    print(f"alerts saved to data/alerts.json")

if __name__ == '__main__':
    import numpy as np
    main()
